config/routes.rb
Rails.application.routes.draw do
  
  devise_for :lehrers
  resources :webquests

  root "webquests#index"

end

app/models/fach.rb
class Fach < ActiveRecord::Base
	has_many :webquests
end

app/models/lehrer.rb
class Lehrer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :webquests
end

app/models/webquest.rb
class Webquest < ActiveRecord::Base

	belongs_to :lehrer
	belongs_to :fach

	has_attached_file :image, styles: {medium: "300x300>"}
	validates_attachment_content_type :image , :content_type => /\Aimage\/.*\Z/

	has_attached_file :anhang
	validates_attachment_content_type :anhang, :content_type => ['application/pdf', 'application/msword', 'text/plain', 
		'application/vnd.openxmlformats-officedocument.wordprocessingml.document']

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/webquests_controller.rb
class WebquestsController < ApplicationController
	before_action :find_webquest, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_lehrer!, except: [:index, :show]

	def index
		if params[:fach].blank?
			@webquests = Webquest.all.order("created_at DESC")
		else
			@fach_id = Fach.find_by(name: params[:fach]).id
			@webquests = Webquest.where(fach_id: @fach_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@webquest = current_lehrer.webquests.build
	end

	def create 
		@webquest = current_lehrer.webquests.build(webquest_params)

		if @webquest.save 
			redirect_to @webquest, notice: "Ihr Webquest wurde erfolgreich erstellt"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @webquest.update(webquest_params)
			redirect_to @webquest, notice: "Der Webquest wurde erfolgreich aktualisiert" 
		else 
			render 'edit'
		end
	end

	def destroy
		@webquest.destroy
		redirect_to root_path
	end


	private

	def webquest_params
		params.require(:webquest).permit(:name, :beschreibung, :fach, :image, :fach_id, :anhang)
	end

	def find_webquest
		@webquest = Webquest.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webquests_helper.rb
module WebquestsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Webquest
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "WebQuest", root_path

			- if lehrer_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Neuer WebQuest", new_webquest_path
					%li= link_to "Mein Profil", edit_lehrer_registration_path
					%li= link_to "Abmelden", destroy_lehrer_session_path , method: :delete
			- else 
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Registrierung", new_lehrer_registration_path
					%li= link_to "Anmelden", new_lehrer_session_path
	
	%nav.navbar.navbar-default
		.container
			%ul.nav.navbar-nav.navbar-right
				%li=link_to "Alle Webquests", root_path	
				-Fach.all.each do |fach|
					%li=link_to fach.name, webquests_path(fach: fach.name)

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class:"alert alert-info"
		=yield

	%footer
		.container
			.col-md-4
				%p Made with <3 by Autori Agentur
			.col-md-8
				%ul.nav.navbar-nav.navbar-right
					%li= link_to 'Was ist Webquest?', page_path('webquest')
					%li= link_to 'Hintergrund', page_path('hintergrund')
					%li= link_to 'Über das Projekt', page_path('projekt')
					%li= link_to 'Impressum', page_path('impressum')

app/views/pages/impressum.html.haml
%h1 Impressum

app/views/webquests/_form.html.haml
= simple_form_for @webquest, html: {multipart: true} do |f|
	-if @webquest.errors.any?
		#errors
			%h2
			=pluralize(@webquest.errors.count, "error")
			prevented this webquest from saving.
			%ul
				-@webquest.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: {class: 'form-control'}

	.form-group
		=f.input :name, input_html: {class: "form-control"}

	.form-group
		=f.input :beschreibung, input_html: {class: "form-control"}

	.form-group
		=f.collection_select :fach_id, Fach.all, :id, :name, {promt: "Unterrichtsfach auswählen" }, input_html: {class: "form-control"}
	.form-group
		=f.input :anhang, input_html: {class: 'form-control'}

	=f.button  :submit , "Webquest erstellen" , class: "btn btn-primary"

app/views/webquests/edit.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Aktualisierung des Webquests
			.panel-body
				%strong.center Aktuelles Bild
				%br/ 
				= image_tag @webquest.image.url(:medium)

				= render 'form'

app/views/webquests/index.html.haml
#pins.transitions-enabled
	- @webquests.each do  |webquest|
		.box.panel.panel-default
			= link_to (image_tag webquest.image.url), webquest
			.panel-body
			%h2= link_to webquest.name, webquest
			%p.user
				Erstellt von
				=webquest.lehrer.vorname 
				=webquest.lehrer.name 

app/views/webquests/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Neuer Webquest
			.panel-body
				= render 'form'

app/views/webquests/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @webquest.image.url
			.panel-body
				%h1= @webquest.name
				%p.description= @webquest.beschreibung
			- if @webquest.anhang?	
				.panel-body
					%h3 Anhang
					%p.description= link_to "Aufgabe herunterladen",  @webquest.anhang.url(:original, false)
			.panel-footer
				.row
					.col-md-6
						%p.user
						Erstellt von
						=@webquest.lehrer.vorname 
						=@webquest.lehrer.name 
					.col-md-6
						.btn-group.pull-right
							- if lehrer_signed_in?
								= link_to "Aktualisieren", edit_webquest_path, class: "btn btn-default"
								= link_to "Löschen", webquest_path, method: :delete, data: {confirm: "Sind Sie sicher?"}, class: "btn btn-default"